### ISSUE TITLE
Can't add toolbar above numberPad

### ISSUE THREAD

**Issue by nikoagge** [Sunspension/VKPinCodeView#11]
I want  to add a doneToolbar above numberPad to dismiss it when I want, but can't implement it, although I 've seen several tutorials. The code that I 've trying to implement is this:

let toolBar = UIToolbar(frame: CGRect(origin: .zero, size: .init(width: self.frame.size.width, height: 40)))
        
        let flexSpace = UIBarButtonItem(barButtonSystemItem: .flexibleSpace, target: nil, action: nil)
        let doneButton = UIBarButtonItem(title: "Done", style: .done, target: self, action: #selector(dismissNumberPad(_:)))
        
        toolBar.setItems([flexSpace, doneButton], animated: false)
        toolBar.sizeToFit()
        
        _textField.inputAccessoryView = toolBar

Any suggestions why is this happening?

**Comment by Sunspension** [comment]
@nikoagge Have you checked whether your code execute on debug? Because I have no issues and I can see toolbar above the keyboard
