### ISSUE TITLE
Set Cursor Color

### ISSUE THREAD

**Issue by EmreSURK** [Sunspension/VKPinCodeView#13]
Hi, thanks for the great library. 

Is there any option to set the cursor color? It would be nice if we provide that option. 

I can try adding that functionality if you open pull requests :) 

Best.

**Comment by Sunspension** [comment]
Basically you can set your own style with any colours you want

**Comment by Sunspension** [comment]
If you do not have any questions I will close this, feel free to contact with me if you need something else.
