### ISSUE TITLE
How to make the fields empty ? 

### ISSUE THREAD

**Issue by infaz** [Sunspension/VKPinCodeView#2]
After an error, I want remove already entered text from the field. Then, user can enter value from beginning.

**Comment by Sunspension** [comment]
Hi, thank you for interest to my project. Right now logic does not support automatic reset entered values after error, but it is not a problem to add that feature. Please wait for next release.

**Comment by infaz** [comment]
@Sunspension yes please, Im waiting for the next release
Thanks Bro.
