### ISSUE TITLE
Value of type 'VKPinCodeView' has no member 'setStyle'

### ISSUE THREAD

**Issue by SparklingAir** [Sunspension/VKPinCodeView#3]
There are project sources that compile on one computer and do not compile on another with the error above. 
The first computer has these versions:
macOS Mojave and XCode 11.2.1
the second:
macOS Catalina Beta 10.15.2 (19C46a) and XCode 11.2.1
I have updated gem, cocoapods, pods...

**Comment by Sunspension** [comment]
I guess that you need to clear Cocoapods cache. 

`pod cache clean VKPinCodeView --all` or `pod cache clean --all`

And just in case you can delete Pods/VKPinCodeView folder from your project folder

**Comment by SparklingAir** [comment]
It did not help

**Comment by Sunspension** [comment]
Try this one `pod cache clean --all` and after that try `pod update VKPinCodeView`

**Comment by SparklingAir** [comment]
alas, all the same :(

**Comment by Sunspension** [comment]
Could you provide your code somehow? Because I have created a project from scratch and have no issues.

**Comment by SparklingAir** [comment]
I'm afraid I have no right to post the code here. May I show it to you personally?

**Comment by Sunspension** [comment]
Yes, please use my email address, you can find it on README. 
But before I would ask you also to check your implementation and latest example from the source.
Anyway you are welcome to send me your implementation.
