### ISSUE TITLE
Please update the isError public

### ISSUE THREAD

**Issue by EnasAhmedZaki** [Sunspension/VKPinCodeView#4]
Thanks for this pod and all your effort.
I was using the older version (0.1.9) when I tried to update the pod to version(0.3.0).
I found out that `isError` variable is `Private`.
I'm doing the OTP code check at server side, so I have to wait for the API response to show error or proceed with my flow.
Could you please fix this or provide another solution for it?

Appreciate your quick response. Thanks!

**Comment by Sunspension** [comment]
Hello, thank you for your feedback. 
I see, yes it is a bug, please use the older one version. 
I will fix that in the next release.

**Comment by Sunspension** [comment]
The problem has been fixed, please update to the latest version.
