### ISSUE TITLE
VKPinCodeView freezes

### ISSUE THREAD

**Issue by israahamed112** [Sunspension/VKPinCodeView#5]
Hello 
there is an issue  with this flow : when the screen which include VKPINCodeView appears and then another screen present and then I dismiss to go to the screen of VKPInCodeView again the screen freezes :( 
note : sometimes with first dismiss and sometimes which second dismiss or when I repeat
this flow 

Thanks for this pod and all your effort.

**Comment by Sunspension** [comment]
Hello, thank you for your feedback, could you provide a simple example to reproduce the problem? It will help me to understand the exact your case. You can send that example by email, my email address you will find in README. Thank you.

**Comment by Sunspension** [comment]
So, in reason that you didn't provide your code example I've created my own implementation by your description and I've got no issues.
