### ISSUE TITLE
How to UI test it?

### ISSUE THREAD

**Issue by ppamorim** [Sunspension/VKPinCodeView#9]
Hi, I am trying to type a security PIN in an `XCTestCase` but I could not do it so far.

Tried these both below, no success:

```swift
app.descendants(matching: .any)["securityPinView"].textFields.element(boundBy: 0).typeText("1111")
app.textFields["securityPinView"].typeText("1111")
```

Being `securityPinView` the `accessibilityIdentifier` value.

**Comment by Sunspension** [comment]
@ppamorim I guess you need to simulate pressing buttons on the virtual keyboard.

**Comment by ppamorim** [comment]
@Sunspension What I did was to use this function to type the desired password:

```swift
private func typeKey(_ keyString: String) {
    let appKeys = app.keys
    let keysMapped = keyString.map { key in appKeys[String(key)] }
    for index in 0..<keysMapped.count {
        keysMapped[index].tap()
        if index == keysMapped.count - 1 {
            Thread.sleep(forTimeInterval: 0.5)
        }
    }
}
````

To use it just call like this:

```swift
typeKey("5555")
```
